# -*- coding: utf-8 -*-
"""AHI_504_Assignment1_Sept18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pX6sMtFCDq00n-EcO1sbzrX0GVQhX3NZ
"""

import pandas as pd 
import sqlalchemy
from sqlalchemy import create_engine

!pip install pymysql
import pymysql

fakeDataset = pd.DataFrame({'colors' : ['blue', 'purple', 'pink']})

MYSQL_HOSTNAME = '20.62.193.224'
MYSQL_USER = 'manleenchhabra'
MYSQL_PASSWORD = 'manleenchhabra2021'
MYSQL_DATABASE = 'ahi'

connection_string = f'mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOSTNAME}:3305/{MYSQL_DATABASE}'
engine = create_engine(connection_string)

TABLENAME = MYSQL_USER + 'fakeTableAssignment1'

fakeDataset.to_sql(TABLENAME, con=engine)